<?php 
 include 'connection.php';

 $insert = "
INSERT INTO `products` (`id`, `name`, `price`, `product_detail`, `image`) VALUES
(2, 'pure honey', '200', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '9.png'),
(3, 'row honey', '300', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '0.jpg'),
(4, 'honey', '100', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '0.png'),
(5, 'Honey Bee Raw Honey ', '300', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '1-1-330x300.png'),
(6, 'Chaayos Wild Forest', '150', Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '2.png'),
(7, 'Eco Sprig Cinnamon', '240', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '3.png'),
(8, 'Honey And Spice Mangrove ', '300', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '3-1-330x300.jpg'),
(9, 'organic joney', '400', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '4-330x300.jpg'),
(10, 'pure natural honey', '150', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '5.png'),
(11, 'Honey  Raw Honey ', '250', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '7.jpg'),
(12, 'Honey Spice Mangrove ', '190', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '6.png'),
(13, 'Eco Sprig Cinnamon2', '400', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '10.jpg'),
(14, 'Honey  Mangrove ', '240', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '9-330x300.jpg'),
(15, 'h', '350', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '15-330x300.jpg'),
(16, 'honey cinammen', '220', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '14-330x300.jpg'),
(17, 'Honey  Raw ', '334', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '1.png'),
(18, 'honey organic', '444', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '12-330x300.jpg'),
(19, 'Mangrove  Honey  ', '545', 'Natural bee honey is a precious bee product, recognized for its multiple nutritional and medicinal benefits. This honey, collected by bees from the nectar of various flowers, is distinguished by its specific aroma, color and taste, which varies from light golden shades to dark brown. Rich in natural sugars such as fructose and glucose, natural honey also contains vitamins, minerals, enzymes and antioxidants. Its antibacterial and antifungal properties make it valuable not only in food, but also in natural treatments. Its complex aroma and unmistakable sweet taste turn natural bee honey into a versatile and healthy food.', '10-330x300.jpg');


 ";
 $result = mysqli_query($conn, $insert);
 if ($result) {
 	echo 'inserted';
 }
?>